### ISSUE TITLE
Ref-style link definition syntax: COLON missing?

### ISSUE THREAD

**Issue by tin-pot** [cirosantilli/markdown-style-guide#3]
Nice work, and a useful idea to collect guidelines like this!

One issue though: I think the examples for _definitions of reference-style links_, like for example:

```
[id2]     http://long-url.com
```

[(line 1611 ff)](https://github.com/cirosantilli/markdown-style-guide/blame/gh-pages/index.md#L1611) are missing the "`:`" after the "`]`", and thus should read instead:

```
[id2]:     http://long-url.com
```

At least that's what [Gruber's](http://daringfireball.net/projects/markdown/syntax#link) and the _[CommonMark](http://spec.commonmark.org/0.23/#link-reference-definition)_ rules require, if I see this right.

**Comment by cirosantilli** [comment]
Thanks!
