### ISSUE TITLE
Add rule "Do not ident first level of lists"

### ISSUE THREAD

**Issue by koppor** [cirosantilli/markdown-style-guide#6]
There is a rule [spaces-after-list-marker](https://github.com/cirosantilli/markdown-style-guide/blob/gh-pages/index.md#spaces-after-list-marker) and a rule for [indentation inside lists](https://github.com/cirosantilli/markdown-style-guide/blob/gh-pages/index.md#indentation-of-content-inside-lists), but no rule for spaces before the first list item.

Proposal:

## No spaces before first list marker

Do not indent a list itself.

When beginning a list, just start it and do not add any additional level indentation.

Bad:

```
  - a
  - b
```

Good:

```
- a
- b
```

**Comment by koppor** [comment]
Refs [MD-0006](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md006---consider-starting-bulleted-lists-at-the-beginning-of-the-line) of [markdown-lint](https://github.com/DavidAnson/markdownlint).

**Comment by cirosantilli** [comment]
Yes, thanks! There are all kinds of crazy things people do with Markdown that I don't even think about :-)
